version: "3.8" # Specify docker-compose version

services:
  mongodb:
    image: mongo:latest # Use the latest official MongoDB image
    container_name: book-mongo-db # Name the container
    ports:
      - "27017:27017" # Map host port 27017 to container port 27017
    volumes:
      - mongo-book-data:/data/db # Use a named volume for data persistence
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  mongo-book-data: # Define the named volume
    driver: local
